config/routes.rb
Zinlot::Application.routes.draw do

  get "campaigns/index"
  get "about_us" => "marketing#about_us"
  get "contact_us" => "marketing#contact_us"
  get "how_it_works" => "marketing#how_it_works"
  get "how_it_helps" => "marketing#how_it_helps"
  resources :campaigns

  resources :reports

  devise_for :users
  resources :users
  get 'settings' => 'users#index'
  get 'alerts' => 'alerts#index'
  
  resources :devices

  get "cars" => 'cars#index'
  get "live-inventory" => "live_location#index"
  get "map/index"
  get "devices" => "devices#index"
  get "vehicles" => 'vehicles#index'
  get 'dashboard/index' => 'dashboard#index', as: :user_root
  get 'test-drives' => 'historical_trips#index'
  get 'test-drives/week' => 'historical_trips#week'
  get 'test-drives/:id' => 'historical_trips#show'
  get 'dtc-codes/:code' => 'dtc_codes#show'

  resources :historical_trips
  resources :geofence_violations
  resources :device_histories
  resources :alerts

  devise_for :admin_users, ActiveAdmin::Devise.config

  root 'marketing#index'
  ActiveAdmin.routes(self)

end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_protected :created_at

  belongs_to :vehicle

  has_many :historical_trips, primary_key: :imei
  has_many :alert
  has_one :car
  
  has_one :customer

  has_many :device_histories, primary_key: :imei
  
  scope :has_open_issues, -> { where(has_open_issue: true) }

  def latest_trip
    historical_trips.last
  end

  def self.duration_time(duration: duration)
    time = Time.at(duration/1000).utc.strftime('%H:%M:%S')
    time.sub(/^00:/, '')
  end

  def formatted_issues
    issues = []
    if battery_issue
      issues.push 'Low battery'
    end
    if dtc_issue
      issues.push 'DTC'
    end

    issues.join(', ')
  end

  def self.miles_rounded(miles: miles); miles.round(2); end

  def latest_vbatt
    if latest_history
      latest_history[:vbatt]
    end
  end

  def latest_dtc
    if latest_history
      latest_history[:dtc_codes]
    end
  end

  def battery_issue
    latest_history && latest_history[:has_low_batt]
  end

  def dtc_issue
    latest_history && latest_history[:has_dtc]
  end

  def latest_history
    if latest_history_id
      DeviceHistory.find(latest_history_id)
    end
  end

  def status
    heartbeats_in_last_24 = device_histories.where('created_at > ?', 1.day.ago).count

    if heartbeats_in_last_24 > 0
      'glyphicon glyphicon-ok'
    else
      'glyphicon glyphicon-warning-sign'
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @search = Device.search(params[:q])
    #@search = Device.includes(:vehicle => [:car, :vehicle_usage]).search(params[:q])
    #@devices = Device.all
    @devices = @search.result
    @mobile_ids = @devices.pluck('imei')
    
    @car_names = {}
    @devices.each {|d| @car_names["#{d['imei']}"] = "#{d['name']}"}
    @latest_readings = Reading.latest_readings(mobile_ids: @mobile_ids)
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    trips = @device.historical_trips
    @engine_hours = Device.duration_time(duration: trips.sum('duration'))
    @total_trips = trips.count
    @total_miles = trips.last && Device.miles_rounded(miles: trips.last[:ending_mileage])
    @vbatt_readings = Reading.where(mobileId: @device[:imei], eventCode: 26).to_a
    @vbatt_chart_hash = {}
    @vbatt_readings.each do |reading|
      @vbatt_chart_hash[Time.at((reading['updateTime']/1000).round)] = reading['vBatt']
    end
    @current_vbatt = @vbatt_readings[@vbatt_readings.count-1]['vBatt']
    readings_with_dtc_codes = Reading.where(mobileId: @device.imei, dtcCount: {:"$gt" => 0})
    @previous_dtc_codes = {}
    readings_with_dtc_codes.each do |reading|
      time = Time.at(reading['updateTime']/1000).strftime('%m/%d %I:%M %p')
      @previous_dtc_codes[time] = []
      dtc_codes = reading['dtcCodes'].split(',')
      for dtc_code in dtc_codes
        @previous_dtc_codes[time].push(Reading.dtc_description(dtc_code))
      end
    end
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params[:device]
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%script{src:'http://maps.google.com/maps/api/js?sensor=false&libraries=visualization,geometry,places'}
%script{src:'http://jquery-ui-map.googlecode.com/svn/trunk/ui/jquery.ui.map.js'}

#map-controls.panel.panel-default{style: 'position:absolute; z-index:1000002'}
  .panel-heading{style: 'padding-top:10px'}
    .btn-group
      %button#zoom-out.btn.btn-default
        %i.glyphicon.glyphicon-zoom-out
      %button#zoom-in.btn.btn-default
        %i.glyphicon.glyphicon-zoom-in
        
    .btn-group#map-type-select{data: {toggle: 'buttons'}}
      %label.active.btn.btn-default
        %input{type: 'radio', name: 'map-type', id: 'ROADMAP'}
        %i.glyphicon.glyphicon-road
      %label.btn.btn-default
        %input{type: 'radio', name: 'map-type', id: 'SATELLITE'}
        %i.glyphicon.glyphicon-globe
  .panel-heading
    %h4.panel-title
      %a.btn.btn-default{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
        %i.glyphicon.glyphicon-filter
        Filters
  #collapseOne.panel-collapse.collapse{class: params[:q] && 'in'}
    .panel-body
      = search_form_for @search, {html:{class:'form-inline'}} do |f|
        .form-group
          = f.text_field :vehicle_car_year_cont, placeholder: "Year", class: 'form-control'
        .form-group
          = f.text_field :vehicle_car_make_cont, placeholder: "Make", class: 'form-control'
        .form-group
          = f.text_field :vehicle_car_model_cont, placeholder: "Model", class: 'form-control'

        .row{style: 'margin-left:0'}
          .form-group
            = f.text_field :vehicle_vehicle_usage_name_cont, placeholder: "Usage", class: 'form-control'
          .form-group
            = f.text_field :vehicle_vin_cont, placeholder: "VIN", class: 'form-control'
          .form-group
            = f.text_field :vehicle_car_color_cont, placeholder: "Color", class: 'form-control'
          .form-group
            %button{type: 'submit', class: 'btn btn-primary'}
              %i.glyphicon.glyphicon-search
          .form-group{style: 'margin-right: 15px'}
            = link_to 'Clear', '/devices'
            
        .row{style: 'margin-left:0'}
          .form-group
            %label.checkbox-inline
              = f.check_box :has_open_issue_true
              ONLY open issues

  .panel-heading
    %h4.panel-title
      %a.btn.btn-default{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseTwo"}
        %i.glyphicon.glyphicon-th-list
        Vehicles
  #collapseTwo.panel-collapse.collapse{class: params[:q] && 'in'}
    .panel-body
      %table.table.table-condensed
        %thead
          %tr
            %th Status
            %th Year Make Model
            %th Usage
            %th Battery
            %th DTC
            %th VIN
            %th Car Color

        - @devices.each do |device|
          %tr
            %td.ac
              %i{class: device.status}
            %td
              = link_to device.vehicle.car.name, device_path(device)
            %td= device.vehicle.vehicle_usage.name
            %td{class: device.battery_issue && 'dk-red'}= device.latest_history && "#{device.latest_history.vbatt}v"
            %td= device.dtc_issue ? link_to('active', device_path(device)) : ''
            %td= device.vehicle.vin
            %td= device.vehicle.car_color

#map_canvas

:coffeescript
  $('#zoom-in').click ->
    map = $('#map_canvas').gmap('get', 'map')
    map.setZoom(map.getZoom()+1)
  
  $('#zoom-out').click ->
    map = $('#map_canvas').gmap('get', 'map')
    map.setZoom(map.getZoom()-1)

  $('#map-type-select input').on 'change', ->
    map = $('#map_canvas').gmap('get', 'map')
    map.setMapTypeId google.maps.MapTypeId[$('#map-type-select input:checked')[0].id]

  google.maps.visualRefresh = true
  gateway = new Pusher("f513119581ede36ac6c4").subscribe "gateway"
  carNames = #{@car_names.to_json}
  latestReadings = #{@latest_readings.to_json}

  addMarker = (reading) ->
    for k,v of reading
      [latitude, longitude] = [v[1], v[0]]
      mobileId = String(k)

    $('#map_canvas').gmap 'addMarker',
      animation : google.maps.Animation.DROP
      bounds    : true
      mobileId  : [mobileId]
      position  : (new google.maps.LatLng(latitude, longitude))
      icon      : 'http://chart.googleapis.com/chart?chst=d_simple_text_icon_above&chld=' + carNames[mobileId] + '|16|bf6410|car-dealer|16|bf6410|FFF'

  gateway.bind 'message', (reading) ->
    $('#map_canvas').gmap 'find', 'markers', { 'property':'mobileId', 'value':reading.mobileId }, (marker, found) ->
      if found
        marker.setPosition(new google.maps.LatLng(reading.geo.coordinates[1], reading.geo.coordinates[0]))

  $('#map_canvas').gmap({disableDefaultUI: true}).bind 'init', ->
    latestReadings.forEach addMarker

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%h3= @device.vehicle.car.name

.row
  .col-xs-4
    .panel.panel-default
      .panel-heading Summary
      .panel-body
        %p
          %strong Engine Hours:
          = @engine_hours

        %p
          %strong Trips:
          = @total_trips

        %p
          %strong Miles Driven:
          = @total_miles

        %p
          %strong Battery:
          = @current_vbatt
  .col-xs-4
    .panel.panel-default
      .panel-heading
        Current Issues&nbsp;
        %span#dtc-count.badge.badge-muted 0

      %ul.list-group
        %li.list-group-item
          %div
            %strong Engine:

            - if @device.dtc_issue

              - dtc_codes = @device.latest_history.dtc_codes.split(',')

              :coffeescript
                $('#dtc-count').text #{dtc_codes.count}

              %ul{style: 'list-style-type:none; padding-left:0'}

                - dtc_codes.each do |dtc_code|
                  - dtc_details = Reading.dtc_description(dtc_code)
                  %li{style:'padding-bottom:10px'}
                    %a.toggler{id: dtc_code}= dtc_details[:description]

                    %div{id: "#{dtc_code}-details", style: 'display:none; padding-top:10px'}
                      %strong Causes
                      = raw(dtc_details[:causes])
                      %strong Solutions
                      = raw(dtc_details[:solutions])

              :coffeescript
                $('a.toggler').bind 'click', (e) ->
                  $('#' + e.target.id + '-details').toggle()

                window.toggleDtcDetails = (divId) ->
                  $('#' + divId).toggle()

            - else
              No issues.

        %li.list-group-item
          %div
            %strong Battery:
            No issues.



.panel.panel-default
  .panel-heading Battery History
  .panel-body= line_chart @vbatt_chart_hash