config/routes.rb
Zinlot::Application.routes.draw do

  get "campaigns/index"
  get "about_us" => "marketing#about_us"
  get "contact_us" => "marketing#contact_us"
  get "how_it_works" => "marketing#how_it_works"
  get "how_it_helps" => "marketing#how_it_helps"
  resources :campaigns

  resources :reports

  devise_for :users
  resources :users
  get 'settings' => 'users#index'
  get 'alerts' => 'alerts#index'
  
  resources :devices

  get "cars" => 'cars#index'
  get "live-inventory" => "live_location#index"
  get "map/index"
  get "devices" => "devices#index"
  get "vehicles" => 'vehicles#index'
  get 'dashboard/index' => 'dashboard#index', as: :user_root
  get 'test-drives' => 'historical_trips#index'
  get 'test-drives/week' => 'historical_trips#week'
  get 'test-drives/:id' => 'historical_trips#show'
  get 'dtc-codes/:code' => 'dtc_codes#show'

  resources :historical_trips
  resources :geofence_violations
  resources :device_histories
  resources :alerts

  devise_for :admin_users, ActiveAdmin::Devise.config

  root 'marketing#index'
  ActiveAdmin.routes(self)

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :notification_emails, :notification_phone_nbrs, :email_notifications, :sms_notifications

  scope :with_email_notification, lambda { |event| {:conditions => "email_notifications_mask & #{2**EVENTS.index(event.to_s)} > 0 "} }
  scope :with_sms_notification, lambda { |event| {:conditions => "sms_notifications_mask & #{2**EVENTS.index(event.to_s)} > 0 "} }

  EVENTS = Alert::EVENTS

  def email_notifications=(events)
    self.email_notifications_mask = (events.to_a & EVENTS).map { |e| 2**EVENTS.index(e) }.sum
  end

  def email_notifications
    EVENTS.reject { |e| ((email_notifications_mask || 0) & 2**EVENTS.index(e)).zero? }
  end

  def email_notification_symbols
    email_notifications.map(&:to_sym)
  end

  def sms_notifications=(events)
    self.sms_notifications_mask = (events.to_a & EVENTS).map { |e| 2**EVENTS.index(e) }.sum
  end

  def sms_notifications
    EVENTS.reject { |e| ((sms_notifications_mask || 0) & 2**EVENTS.index(e)).zero? }
  end

  def sms_notification_symbols
    sms_notifications.map(&:to_sym)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include AngularController

  def index
    @reports = Report.all
    @users = User.where(id: current_user)
    @current_user = User.find(current_user)
    respond_with @users
  end

  def update
    @user = User.find(params[:id])
    respond_with @user.update(params.permit(:notification_emails, :notification_phone_nbrs, :email_notifications, :sms_notifications, email_notifications: [], sms_notifications: []))
  end

end

app/views/users/index.html.haml
- content_for :ng_app, 'zin'

#settings-index{ng: {controller: "UserCtrl"}, style: 'max-width: 400px'}

  %legend
    %i.glyphicon.glyphicon-user
    Contact Information

  .form-group
    %label Phone numbers

    .input-group{ng: {repeat: "phoneNumber in phoneNumbers()"}}
      %input.form-control{value: "{{ phoneNumber | tel }}"}

      %span.input-group-btn
        %button.btn.btn-default{ng: {click: "removePhoneNumber({{ $index }})"}}
          %i.glyphicon.glyphicon-remove-sign

    %form.form{name: "addPhoneNumberForm", ng: {submit: "addPhoneNumber(addPhoneNumberForm)"}}
      .input-group
        %input.form-control{type: "number", ng: {minlength: "10", model: "newPhoneNumber"}, placeholder: "Add phone number"}

        %span.input-group-btn
          %button.btn.btn-default{type: "submit"}
            %i.glyphicon.glyphicon-plus

      %p.help-block{ng: {show: "addPhoneNumberForm.$error.minlength"}} Enter a 10-digit phone number


  .form-group
    %label Email addresses

    .input-group{ng: {repeat: "email in emails()"}}
      %input.form-control{value: "{{ email }}"}

      %span.input-group-btn
        %button.btn.btn-default{ng: {click: "removeEmail({{ $index }})"}}
          %i.glyphicon.glyphicon-remove-sign

    %form.form{name: "addEmailForm", ng: {submit: "addEmail(addEmailForm)"}}
      .input-group
        %input.form-control{type: "email", ng: {model: "newEmail"}, placeholder: "Add email"}

        %span.input-group-btn
          %button.btn.btn-default{type: "submit"}
            %i.glyphicon.glyphicon-plus

      %p.help-block{ng: {show: "addEmailForm.$error.email"}} Enter a valid email


  %legend
    %i.glyphicon.glyphicon-warning-sign
    &nbsp;Alert Subscriptions

  %ul.list-group#notification-setup

    %li.list-group-item
      .row
        Geofence Enter
        .btn-group.pull-right{data: {toggle: 'buttons'}}
          %label.btn
            -# TODO: implement ng-class instead of Ruby hack
            %button.btn{ng: {click: "toggleNotification('GEOFENCE_ENTER', 'email')"}, class: @current_user.email_notifications.include?('GEOFENCE_ENTER') && 'active'}
              %i.glyphicon.glyphicon-envelope

          %label.btn
            %button.btn{ng: {click: "toggleNotification('GEOFENCE_ENTER', 'sms')"}, class: @current_user.sms_notifications.include?('GEOFENCE_ENTER') && 'active'}
              %i.glyphicon.glyphicon-phone

    %li.list-group-item
      .row
        Geofence Exit
        .btn-group.pull-right{data: {toggle: 'buttons'}}
          %label.btn
            %button.btn{ng: {click: "toggleNotification('GEOFENCE_EXIT', 'email')"}, class: @current_user.email_notifications.include?('GEOFENCE_EXIT') && 'active'}   
              %i.glyphicon.glyphicon-envelope

          %label.btn
            %button.btn{ng: {click: "toggleNotification('GEOFENCE_EXIT', 'sms')"}, class: @current_user.sms_notifications.include?('GEOFENCE_EXIT') && 'active'}   
              %i.glyphicon.glyphicon-phone

    %li.list-group-item
      .row
        Engine Trouble Codes
        .btn-group.pull-right{data: {toggle: 'buttons'}}
          %label.btn
            %button.btn{ng: {click: "toggleNotification('DTC', 'email')"}, class: @current_user.email_notifications.include?('DTC') && 'active'}
              %i.glyphicon.glyphicon-envelope

          %label.btn
            %button.btn{ng: {click: "toggleNotification('DTC', 'sms')"}, class: @current_user.sms_notifications.include?('DTC') && 'active'}
              %i.glyphicon.glyphicon-phone

    %li.list-group-item
      .row
        Low Battery
        .btn-group.pull-right{data: {toggle: 'buttons'}}
          %label.btn
            %button.btn{ng: {click: "toggleNotification('LOW_BATT', 'email')"}, class: @current_user.email_notifications.include?('LOW_BATT') && 'active'}
              %i.glyphicon.glyphicon-envelope

          %label.btn
            %button.btn{ng: {click: "toggleNotification('LOW_BATT', 'sms')"}, class: @current_user.sms_notifications.include?('LOW_BATT') && 'active'}
              %i.glyphicon.glyphicon-phone

    %li.list-group-item
      .row
        Ignition On
        .btn-group.pull-right{data: {toggle: 'buttons'}}
          %label.btn
            %button.btn{ng: {click: "toggleNotification('IGNITION_ON', 'email')"}, class: @current_user.email_notifications.include?('IGNITION_ON') && 'active'}
              %i.glyphicon.glyphicon-envelope

          %label.btn
            %button.btn{ng: {click: "toggleNotification('IGNITION_ON', 'sms')"}, class: @current_user.sms_notifications.include?('IGNITION_ON') && 'active'}
              %i.glyphicon.glyphicon-phone
  %legend
    %i.glyphicon.glyphicon-list-alt
    &nbsp;Report Subscriptions
  
  .panel.panel-default             
  
    .panel-body
      %table.table.table-hover
        %thead
          %tr
            %th Name       
            %th Frequency
            %th
        %tbody
        - @reports.each do |report|
          %tr{class: 'clickToShow', id: "#{report.id}"}
            %td
              %i{class: file_format_icon(report.format)}
              &nbsp;
              = report.name
            %td= frequency_formatted(report.interval) + ' @ ' + report.time.strftime('%l:%M %p')
            %td.action-icons
              = link_to(edit_report_path(report), {}) do
                %i.glyphicon.glyphicon-pencil  
                
              = link_to(report, {:method => :delete, :data => { :confirm => 'Are you sure?' }}) do
                %i.glyphicon.glyphicon-minus-sign
      
      = link_to 'New', new_report_path, class: 'btn btn-success'
      
:coffeescript
  $ ->
    $('.clickToShow').on 'click', (e) ->
      window.location = window.location.protocol + '//' + window.location.host + '/reports/' + e.currentTarget.id + '/edit'