config/routes.rb
Zinlot::Application.routes.draw do

  get "campaigns/index"
  get "about_us" => "marketing#about_us"
  get "contact_us" => "marketing#contact_us"
  get "how_it_works" => "marketing#how_it_works"
  get "how_it_helps" => "marketing#how_it_helps"
  resources :campaigns

  resources :reports

  devise_for :users
  resources :users
  get 'settings' => 'users#index'
  get 'alerts' => 'alerts#index'
  
  resources :devices

  get "cars" => 'cars#index'
  get "live-inventory" => "live_location#index"
  get "map/index"
  get "devices" => "devices#index"
  get "vehicles" => 'vehicles#index'
  get 'dashboard/index' => 'dashboard#index', as: :user_root
  get 'test-drives' => 'historical_trips#index'
  get 'test-drives/week' => 'historical_trips#week'
  get 'test-drives/:id' => 'historical_trips#show'
  get 'dtc-codes/:code' => 'dtc_codes#show'

  resources :historical_trips
  resources :geofence_violations
  resources :device_histories
  resources :alerts

  devise_for :admin_users, ActiveAdmin::Devise.config

  root 'marketing#index'
  ActiveAdmin.routes(self)

end

app/models/alert.rb
require 'twilio-ruby'

class Alert < ActiveRecord::Base
  attr_protected :created_at

  after_save :send_sms
  
  #after_save :send_alert_to_subscribed_users

  belongs_to :device, primary_key: :imei

  validates_presence_of :device_id

  EVENTS = %w[GEOFENCE_ENTER GEOFENCE_EXIT LOW_BATT DTC IGNITION_ON]
  
  def event=(event)
    self.event_type = EVENTS.index(event)
  end
  
  def event
    if event_type
      EVENTS[event_type]
    else
      ''
    end
  end
  
  def send_sms
    #return unless Rails.env == 'production'

    if event == 'GEOFENCE_ENTER'
      message = geofence_enter_message
    elsif event == 'GEOFENCE_EXIT'
      message = geofence_exit_message
    elsif event == 'LOW_BATT'
      message = low_batt_message
    elsif event == 'DTC'
      message = dtc_message
    elsif event == 'IGNITION_ON'
      message = ignition_on_message
    end

    p '.. message:'
    p message

    return unless message

    sms_recipients = User.with_sms_notification(event)
    email_recipients = User.with_email_notification(event)

    for sms_recipient in sms_recipients

      phone_numbers = sms_recipient.notification_phone_nbrs

      if phone_numbers.present?

        for phone_number in phone_numbers.split(',')

          # put your own credentials here
          account_sid = 'ACd4c11bdd5c3dbeb127d6f42e7c979b6f'
          auth_token = 'bc3f4277d4bcafeaea13fadd1f6062c9'

          # set up a client to talk to the Twilio REST API
          @client = Twilio::REST::Client.new account_sid, auth_token

          @client.account.sms.messages.create(
              :from => '+14806488904',
              #:to => '+16023413321',
              :to => "+1#{phone_number}",
              :body => message
          )
        end
      end
    end

    for email_recipient in email_recipients
      SendGridMailer.alert_message(email_recipient, event, message).deliver
    end
  end

  def geofence_enter_message
    "ENTER Geofence: #{device_id} entered geofence #{Geofence.friendly_name(geofence_id)}"
  end

  def geofence_exit_message
    "EXIT Geofence: #{device_id} left geofence #{Geofence.friendly_name(geofence_id)}"
  end

  def low_batt_message
    if device
      "#{device.imei} has a low battery (#{device.latest_vbatt} volts)"
    end
  end

  def dtc_message
    if device
      dtc_codes = device.latest_dtc && device.latest_dtc.split(',')
      s_if_plural = (dtc_codes && dtc_codes.length > 1) ? 's' : ''
      "#{device.imei} reported engine trouble code#{s_if_plural} #{device.latest_dtc}"
    end
  end

  def ignition_on_message
    "#{device_id} turned ignition on"
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  include AngularController

  skip_before_filter :verify_authenticity_token, only: [:create, :show]
  if Rails.env == 'test'
    skip_before_filter :authenticate_user!
  end
  skip_before_filter :authenticate_user!, only: [:create, :show]
  respond_to :html, :json
  
  def index
    @search = Device.includes(:vehicle => [:car, :vehicle_usage]).search(params[:q])
    @low_batt_checked = false
    @dtc_checked = false
    if params[:q]
      @low_batt_checked = params[:q][:has_low_batt_true] == "1"
      @dtc_checked = params[:q][:has_dtc_true] == "1"
    end
    @devices = @search.result.has_open_issues
    device_ids = @search.result.pluck('imei')
    open_issue_ids = @devices.pluck('latest_history_id')
    @alerts = DeviceHistory.where('id NOT IN (?)', open_issue_ids).where({device_id: device_ids}).includes([:device => {:vehicle => [:car, :vehicle_usage]}])
  end

  def create
    respond_with Alert.create(alert_params)
  end

  def show
    @alert = Alert.find(params[:id])
    render json: @alert
  end

  private
  def alert_params
    params.require(:alert).permit(:device_id, :event, :trip_start_at, :update_time)
  end

end

app/views/alerts/index.html.haml
.panel.panel-default
  .panel-heading
    %h3 Alerts
    = search_form_for @search, url: alerts_path, html: {class:'form-inline', style: 'margin-bottom:20px'} do |f|
      .row{style: 'margin-bottom:10px; margin-left:0'}               
        .btn-group#alert-type-toggler{"data-toggle" => "buttons"}
          %label.btn.btn-default{class: @low_batt_checked && 'active'}
            = f.check_box :has_low_batt_true
            %i.glyphicon.glyphicon-flash
            Low battery
          %label.btn.btn-default{class: @dtc_checked && 'active'}
            = f.check_box :has_dtc_true
            %i.glyphicon.glyphicon-warning-sign
            DTC
    
      .row{style: 'margin-bottom:10px; margin-left:0'} 
        .form-group
          = f.text_field :vehicle_car_year_cont, placeholder: "Year", class: 'form-control'
        .form-group
          = f.text_field :vehicle_car_make_cont, placeholder: "Make", class: 'form-control'
        .form-group
          = f.text_field :vehicle_car_model_cont, placeholder: "Model", class: 'form-control'
    
      .row{style: 'margin-left:0'}
        .form-group
          = f.text_field :vehicle_vehicle_usage_name_cont, placeholder: "Usage", class: 'form-control'
        .form-group
          = f.text_field :vehicle_vin_cont, placeholder: "VIN", class: 'form-control'
        .form-group
          = f.text_field :vehicle_car_color_cont, placeholder: "Color", class: 'form-control'
        .form-group
          %button{type: 'submit', class: 'btn btn-primary'}
            %i.glyphicon.glyphicon-search
        .form-group
          = link_to 'Clear', '/alerts'
  .box-header-nested
    %ul.nav.nav-tabs
      %li.active
        %a{href: '#open-issues', data: {toggle: 'tab'}} Open issues
      %li
        %a{href: '#resolved-issues', data: {toggle: 'tab'}} Resolved issues
  .panel-body
    .tab-content
      .tab-pane.active#open-issues
        %table.table
          %thead
            %tr
              %th Vehicle
              %th Issues  
              %th Usage
              %th VIN
              %th Time
        
          %tbody
            - for device in @devices
              %tr
                %td= device.vehicle.name
                %td
                  %a{href: "/devices/#{device.id}"}= device.latest_history && device.latest_history.formatted_issues
                %td= device.vehicle.vehicle_usage.name
                %td= device.vehicle.vin
                %td= device.latest_history && distance_of_time_in_words(Time.now, device.latest_history && device.latest_history.created_at)

      .tab-pane#resolved-issues
        %table.table
          %thead
            %tr
              %th Vehicle
              %th Issues  
              %th Usage
              %th VIN
              %th Time
        
          %tbody
            - for alert in @alerts
              - if device = alert.device
                %tr
                  %td= device.vehicle.name
                  %td
                    %a{href: "/devices/#{device.id}"}= device.latest_history && device.latest_history.formatted_issues
                  %td= device.vehicle.vehicle_usage.name
                  %td= device.vehicle.vin
                  %td= device.latest_history && distance_of_time_in_words(Time.now, device.latest_history && device.latest_history.created_at)
              