config/routes.rb
Zinlot::Application.routes.draw do

  get "campaigns/index"
  get "about_us" => "marketing#about_us"
  get "contact_us" => "marketing#contact_us"
  get "how_it_works" => "marketing#how_it_works"
  get "how_it_helps" => "marketing#how_it_helps"
  resources :campaigns

  resources :reports

  devise_for :users
  resources :users
  get 'settings' => 'users#index'
  get 'alerts' => 'alerts#index'
  
  resources :devices

  get "cars" => 'cars#index'
  get "live-inventory" => "live_location#index"
  get "map/index"
  get "devices" => "devices#index"
  get "vehicles" => 'vehicles#index'
  get 'dashboard/index' => 'dashboard#index', as: :user_root
  get 'test-drives' => 'historical_trips#index'
  get 'test-drives/week' => 'historical_trips#week'
  get 'test-drives/:id' => 'historical_trips#show'
  get 'dtc-codes/:code' => 'dtc_codes#show'

  resources :historical_trips
  resources :geofence_violations
  resources :device_histories
  resources :alerts

  devise_for :admin_users, ActiveAdmin::Devise.config

  root 'marketing#index'
  ActiveAdmin.routes(self)

end

app/models/report.rb
class Report < ActiveRecord::Base
  
  attr_protected :created_at
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:q, :interval, :format, :user_id, :name, :time, :time_zone)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
  
  def file_format_icon(file_format)
    case file_format
    when 'xls'
      'icon-file-excel'
    when 'pdf'
      'icon-file-pdf'
    end
  end
  
  def frequency_formatted(interval)
    case interval
      when 1
        'Daily'
      when 7
        'Weekly'
    end
  end
  
end

app/views/reports/_form.html.haml
= form_for @report, remote: true, html: {class: 'form form-signin'} do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    -#= f.text_field :name, class: 'form-control', placeholder: 'Name'
    .btn-group{"data-toggle" => "buttons"}
      %label.btn.btn-default
        = f.radio_button :name, 'Inventory'
        Inventory
      %label.btn.btn-default.active
        = f.radio_button :name, 'Service', checked: true
        Service
      %label.btn.btn-default
        = f.radio_button :name, 'Logistic'
        Logistic
      %label.btn.btn-default
        = f.radio_button :name, 'Exceptions'
        Exceptions
    
  .form-group
    .form-inline
      .form-group
        = f.select :interval, options_for_select([['Daily', 1], ['Weekly', 7]]), {}, {class: 'input-sm form-control'}
      .form-group
        = f.time_select :time, {ampm: true, minute_step: 15}
      .form-group
        = f.select :time_zone, options_for_select([ActiveSupport::TimeZone['Pacific Time (US & Canada)'], ActiveSupport::TimeZone['Arizona'], ActiveSupport::TimeZone['Mountain Time (US & Canada)'], ActiveSupport::TimeZone['Central Time (US & Canada)'], ActiveSupport::TimeZone['Eastern Time (US & Canada)']], '(GMT-07:00) Arizona'), {}, {style: 'max-width:100px'}
  .form-group
    .btn-group#alert-type-toggler{"data-toggle" => "buttons"}
      %label.btn.btn-default.active
        = f.radio_button :format, 'xls', {checked: true}
        %i.icon-file-excel
        Excel
      %label.btn.btn-default
        = f.radio_button :format, 'pdf'
        %i.icon-file-pdf
        PDF
  .form-group.hidden
    = f.label :user_id
    = f.number_field :user_id, value: current_user.id
  
  .form-inline
    .form-group
      -#= f.submit 'Save', class: 'btn btn-primary'
      .btn-group
        %button.btn.btn-primary{:type => "button"} Save
        %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a{:href => "#"} Preview
    .form-group
      = link_to 'Back', settings_path, class: 'btn'

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

app/views/reports/new.html.haml
- content_for :ng_app, 'zin'

%h3 New report subscription

%div{ng: {controller: 'ReportCtrl'}}
  = render 'form'

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Q:
  = @report.q
%p
  %b Interval:
  = @report.interval
%p
  %b Format:
  = @report.format
%p
  %b User:
  = @report.user_id
%p
  %b Name:
  = @report.name
%p
  %b Time:
  = @report.time
%p
  %b Time zone:
  = @report.time_zone

= link_to 'Edit', edit_report_path(@report)
\|
= link_to 'Back', reports_path